USE ROLE SS_DBA;
CREATE NOTIFICATION INTEGRATION STATESTREET_INTEGRATION
  ENABLED = TRUE
  TYPE = QUEUE
  NOTIFICATION_PROVIDER = AZURE_STORAGE_QUEUE
  AZURE_STORAGE_QUEUE_PRIMARY_URI = 'https://devintegrationhub.queue.core.windows.net/snowpipe-integration'
  AZURE_TENANT_ID = '20143499-58e8-4292-9d95-07458902340e';
  
DESC NOTIFICATION INTEGRATION STATESTREET_INTEGRATION;

CREATE STORAGE INTEGRATION STATESTREET_STORAGE_INTEGRATION
  TYPE = EXTERNAL_STAGE
  STORAGE_PROVIDER = AZURE
  ENABLED = TRUE
  AZURE_TENANT_ID = '20143499-58e8-4292-9d95-07458902340e'
  STORAGE_ALLOWED_LOCATIONS = ('azure://devintegrationhub.blob.core.windows.net/dev-snowpipe/state_street');

DESC STORAGE INTEGRATION STATESTREET_STORAGE_INTEGRATION;