USE ROLE SS_DBA;

USE SCHEMA SS_DEV.RAW;

CREATE STAGE STATESTREET_AZURE_STAGE_ACCOUNTPROFILE
  URL = 'azure://devintegrationhub.blob.core.windows.net/dev-snowpipe/state_street/ACCOUNTPROFILE/'
  STORAGE_INTEGRATION = STATESTREET_STORAGE_INTEGRATION;

CREATE STAGE STATESTREET_AZURE_STAGE_ACCOUNTSECURITIES
  URL = 'azure://devintegrationhub.blob.core.windows.net/dev-snowpipe/state_street/ACCOUNTSECURITIES/'
  STORAGE_INTEGRATION = STATESTREET_STORAGE_INTEGRATION;

CREATE STAGE STATESTREET_AZURE_STAGE_CHARACTERISTICS
  URL = 'azure://devintegrationhub.blob.core.windows.net/dev-snowpipe/state_street/CHARACTERISTICS/'
  STORAGE_INTEGRATION = STATESTREET_STORAGE_INTEGRATION;

CREATE STAGE STATESTREET_AZURE_STAGE_CLASSIFICATIONS
  URL = 'azure://devintegrationhub.blob.core.windows.net/dev-snowpipe/state_street/CLASSIFICATIONS/'
  STORAGE_INTEGRATION = STATESTREET_STORAGE_INTEGRATION;

CREATE STAGE STATESTREET_AZURE_STAGE_COUNTRYCALENDAR
  URL = 'azure://devintegrationhub.blob.core.windows.net/dev-snowpipe/state_street/COUNTRYCALENDAR/'
  STORAGE_INTEGRATION = STATESTREET_STORAGE_INTEGRATION;

CREATE STAGE STATESTREET_AZURE_STAGE_FXRATES
  URL = 'azure://devintegrationhub.blob.core.windows.net/dev-snowpipe/state_street/FXRATES/'
  STORAGE_INTEGRATION = STATESTREET_STORAGE_INTEGRATION;

CREATE STAGE STATESTREET_AZURE_STAGE_HOLDINGS
  URL = 'azure://devintegrationhub.blob.core.windows.net/dev-snowpipe/state_street/HOLDINGS/'
  STORAGE_INTEGRATION = STATESTREET_STORAGE_INTEGRATION;

CREATE STAGE STATESTREET_AZURE_STAGE_INDEXSECURITY
  URL = 'azure://devintegrationhub.blob.core.windows.net/dev-snowpipe/state_street/INDEXSECURITY/'
  STORAGE_INTEGRATION = STATESTREET_STORAGE_INTEGRATION;

CREATE STAGE STATESTREET_AZURE_STAGE_INDEXTOTAL
  URL = 'azure://devintegrationhub.blob.core.windows.net/dev-snowpipe/state_street/INDEXTOTAL/'
  STORAGE_INTEGRATION = STATESTREET_STORAGE_INTEGRATION;

CREATE STAGE STATESTREET_AZURE_STAGE_PORTFOLIONODE
  URL = 'azure://devintegrationhub.blob.core.windows.net/dev-snowpipe/state_street/PORTFOLIONODE/'
  STORAGE_INTEGRATION = STATESTREET_STORAGE_INTEGRATION;

CREATE STAGE STATESTREET_AZURE_STAGE_PORTFOLIOTOTAL
  URL = 'azure://devintegrationhub.blob.core.windows.net/dev-snowpipe/state_street/PORTFOLIOTOTAL/'
  STORAGE_INTEGRATION = STATESTREET_STORAGE_INTEGRATION;

CREATE STAGE STATESTREET_AZURE_STAGE_SMF
  URL = 'azure://devintegrationhub.blob.core.windows.net/dev-snowpipe/state_street/SMF/'
  STORAGE_INTEGRATION = STATESTREET_STORAGE_INTEGRATION;

CREATE STAGE STATESTREET_AZURE_STAGE_SPONSORBENCHMARK
  URL = 'azure://devintegrationhub.blob.core.windows.net/dev-snowpipe/state_street/SPONSORBENCHMARK/'
  STORAGE_INTEGRATION = STATESTREET_STORAGE_INTEGRATION;

CREATE STAGE STATESTREET_AZURE_STAGE_TRANSACTIONS
  URL = 'azure://devintegrationhub.blob.core.windows.net/dev-snowpipe/state_street/TRANSACTIONS/'
  STORAGE_INTEGRATION = STATESTREET_STORAGE_INTEGRATION;