USE SCHEMA RAW;

CREATE OR REPLACE SEQUENCE ACCOUNTSECURITIES_SEQ;

CREATE
OR REPLACE TABLE ACCOUNTSECURITIES(
    PRIMARY_KEY INT DEFAULT ACCOUNTSECURITIES_SEQ.NEXTVAL PRIMARY KEY,
    ENTITY_CODE STRING(27) NOT NULL,
    --ASSET_IDENTIFIER STRING(255) NOT NULL, 
    ASSET_IDENTIFIER STRING(255), -- Removed NOT NULL based on sample data
    COUPON_RATE NUMBER(38, 19),
    MATURITY_DATE DATE,
    UNIQUE_SECURITY_ID STRING(255) NOT NULL,
    INVESTMENT_VALUE_EST_METHOD STRING(255), --added STRING(255) based on sample data
    MNTHLY_PERF_EST_METHOD STRING(255), --added STRING(255) based on sample data
    LOC_CURRENCY STRING(3),
    SOURCE_FILENAME STRING(1000),
    SOURCE_FILE_ROW_NUMBER NUMBER(38),
    INGESTION_TIME TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);