USE SCHEMA RAW;
CREATE OR REPLACE SEQUENCE ACCOUNTPROFILE_SEQ;

CREATE
OR REPLACE TABLE ACCOUNTPROFILE (
    PRIMARY_KEY INT DEFAULT ACCOUNTPROFILE_SEQ.NEXTVAL PRIMARY KEY,
    SPONSOR_ID STRING(50) NOT NULL,
    CURRENCY_BASE_CODE STRING(3),
    MNTHLY_PERF_EST_METHOD STRING(255),
    SPECIAL_ENTITY_TYPE STRING(255),
    INCEPTION_DATE DATE,
    ENTITY_VALUE_EST_METHOD STRING(255),
    ENTITY_SHORT_NAME STRING(255),
    ENTITY_CODE STRING(27) NOT NULL,
    INCEPTION_DT_REPORTING DATE,
    ENTITY_NAME STRING(255),
    COMMINGLED_FLG STRING(1),
    DAILY_PERF_CNVRSN_DT DATE,
    DAILY_PERF_FLG STRING(1),
    ENTITY_STATUS_CODE STRING(10),
    CLOSE_DATE_PERFORMANCE DATE,
    INCEPTION_DT_GASB DATE,
    FISCAL_YEAR_END_MNTH STRING(2),
    SOURCE_FILENAME STRING(1000),
    SOURCE_FILE_ROW_NUMBER NUMBER(38),
    INGESTION_TIME TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);