USE SCHEMA RAW;

CREATE OR REPLACE SEQUENCE CLASSIFICATIONS_SEQ;

CREATE
OR REPLACE TABLE CLASSIFICATIONS (
    PRIMARY_KEY INT DEFAULT CLASSIFICATIONS_SEQ.NEXTVAL PRIMARY KEY,
    NODE_REF_ID NUMBER (38, 19),
    NODE_REF_CODE STRING(300),
    NODE_REF_DESC STRING(300),
    NODE_REF_LONG_DESC STRING(300),
    CLASSIFICATION_SCHEME_NM STRING(255),
    CLASSIFICATION_LVL_NM STRING(50),
    ASSET_IDENTIFIER STRING(255) NOT NULL,
    EFFECTIVE_DATE DATE,
    END_DT DATE,
    SOURCE STRING(12),
    SOURCE_FILENAME STRING(1000),
    SOURCE_FILE_ROW_NUMBER NUMBER(38),
    INGESTION_TIME TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);