USE SCHEMA RAW;

CREATE
OR REPLACE TABLE COUNTRYCALENDAR (
    --SNAPSHOT_DATE DATE NOT NULL,
    CALENDAR_DT DATE NOT NULL,
    COUNTRY_CD STRING(50) NOT NULL,
    DAY_TYPE_CD STRING(30),
    MONTH_END_CD STRING(2),
    NEXT_BUSINESS_DT DATE,
    NEXT_MONTH_END_DT DATE,
    PRIOR_BUSINESS_DATE DATE,
    PRIOR_MONTH_END_DT DATE,
    SOURCE_FILENAME STRING(1000),
    SOURCE_FILE_ROW_NUMBER NUMBER(38),
    INGESTION_TIME TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);