USE SCHEMA RAW;

CREATE OR REPLACE SEQUENCE FXRATES_SEQ;

CREATE
OR REPLACE TABLE FXRATES (
    PRIMARY_KEY INT DEFAULT FXRATES_SEQ.NEXTVAL PRIMARY KEY,
    EXCHANGE_SOURCE_CODE STRING(55) NOT NULL,
    CURRENCY_PAIR_CODE STRING(24) NOT NULL,
    EFFECTIVE_DATE DATE NOT NULL,
    SPOT_RATE NUMBER(38, 19),
    SOURCE_FILENAME STRING(1000),
    SOURCE_FILE_ROW_NUMBER NUMBER(38),
    INGESTION_TIME TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);