USE SCHEMA RAW;

CREATE OR REPLACE SEQUENCE HOLDINGS_SEQ;

CREATE
OR REPLACE TABLE HOLDINGS(
    PRIMARY_KEY INT DEFAULT HOLDINGS_SEQ.NEXTVAL PRIMARY KEY,
    SPONSOR_ID STRING(50) NOT NULL,
    ENTITY_CODE STRING(27) NOT NULL,
    ASSET_IDENTIFIER STRING(255) NOT NULL,
    COUPON_RATE NUMBER(38, 19),
    MATURITY_DATE DATE,
    UNIQUE_SECURITY_ID STRING(255) NOT NULL,
    EFFECTIVE_DATE DATE NOT NULL,
    --UNIT_PRICE NUMBER(38, 19),
    UNIT_PRICE STRING(255), -- updated to String as sample data has "". to be verified.
    UNITS_AMOUNT NUMBER(38, 19),
    MARKET_VALUE_DIRTY_LOCAL_AMOUNT NUMBER(38, 19),
    INCOME_ACCRUED_LOCAL_AMOUNT NUMBER(38, 19),
    ACCT_LEVEL STRING(20),
    SOURCE STRING(12),
    LOC_CURRENCY STRING (3),
    SOURCE_FILENAME STRING(1000),
    SOURCE_FILE_ROW_NUMBER NUMBER(38),
    INGESTION_TIME TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);