USE SCHEMA RAW;

CREATE OR REPLACE SEQUENCE INDEXTOTAL_SEQ;

CREATE
OR REPLACE TABLE INDEXTOTAL (
    PRIMARY_KEY INT DEFAULT INDEXTOTAL_SEQ.NEXTVAL PRIMARY KEY,
    ENTITY_CODE STRING(27) NOT NULL,
    EFFECTIVE_DATE DATE NOT NULL,
    DATATYPE STRING(27),
    MARKET_CAP NUMBER(38, 19),
    INDEX_LEVEL NUMBER(38, 19), --changed VERYHIGHPRECISIONDOUBLE to NUMBER
    CURRENCY_CODE STRING(30),
    RETURN NUMBER(38, 19),
    SOURCE_FILENAME STRING(1000),
    SOURCE_FILE_ROW_NUMBER NUMBER(38),
    INGESTION_TIME TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);