USE SCHEMA RAW;

CREATE OR REPLACE SEQUENCE PORTFOLIOTOTAL_SEQ;

CREATE
OR REPLACE TABLE PORTFOLIOTOTAL (
    PRIMARY_KEY INT DEFAULT PORTFOLIOTOTAL_SEQ.NEXTVAL PRIMARY KEY,
    -- REPLACED HIGHPRECISIONDOUBLE TO NUMBER
    -- COLOUM NAME "RETURN" ???
    SPONSOR_ID STRING(50) NOT NULL,
    DATATYPE STRING(27),
    ENTITY_CODE STRING(27) NOT NULL,
    ENTITY_SHORT_NAME STRING(255),
    EFFECTIVE_DATE DATE NOT NULL,
    --RETURN_TYPE NUMBER(26, 6),
    RETURN_TYPE STRING(255), -- changed datatype to String from Number
    BMV NUMBER(26, 6),
    EMV NUMBER(26, 6),
    ABAL NUMBER(26, 6),
    INC NUMBER(26, 6),
    GN_LS NUMBER(26, 6),
    CSH_VAL_ADD NUMBER(26, 6),
    INFLOWS NUMBER(26, 6),
    OUTFLOWS NUMBER(26, 6),
    NCF NUMBER(26, 6),
    RETURN NUMBER(26, 6),
    SOURCE_FILENAME STRING(1000),
    SOURCE_FILE_ROW_NUMBER NUMBER(38),
    INGESTION_TIME TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);