USE SCHEMA RAW;

CREATE OR REPLACE SEQUENCE PORTFOLIONODE_SEQ;

CREATE
OR REPLACE TABLE PORTFOLIONODE (
    PRIMARY_KEY INT DEFAULT PORTFOLIONODE_SEQ.NEXTVAL PRIMARY KEY,
    --CHANGED HIGHPRECISIONDOUBLE TO NUMBER
    SPONSOR_ID STRING(50) NOT NULL,
    ENTITY_CODE STRING(27) NOT NULL,
    ENTITY_SHORT_NAME STRING(255),
    EFFECTIVE_DATE DATE NOT NULL,
    CLSSFN_HIER_SCHM_ID NUMBER(12), -- changed INTEGER(12) to NUMBER(12)
    CLSSFN_HIER_SCHM_NM STRING(255),
    CLSSFN_HIER_LVL2_NM STRING(255),
    CLSSFN_HIER_LVL3_NM STRING(255),
    CLSSFN_HIER_LVL4_NM STRING(255),
    CLSSFN_HIER_LVL5_NM STRING(255),
    CLSSFN_HIER_LVL6_NM STRING(255),
    CLSSFN_HIER_LVL7_NM STRING(255),
    CLSSFN_HIER_LVL8_NM STRING(255),
    CLSSFN_HIER_LVL9_NM STRING(255),
    CLSSFN_HIER_LVL10_NM STRING(255),
    CLSSFN_HIER_LVL11_NM STRING(255),
    CLSSFN_HIER_LVL12_NM STRING(255),
    EMV NUMBER(26, 6),
    ASSET_WGHT_AMT NUMBER(26, 6),
    SOURCE_FILENAME STRING(1000),
    SOURCE_FILE_ROW_NUMBER NUMBER(38),
    INGESTION_TIME TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);