USE SCHEMA RAW;

CREATE OR REPLACE SEQUENCE SMF_SEQ;

CREATE
OR REPLACE TABLE SMF(
    PRIMARY_KEY INT DEFAULT SMF_SEQ.NEXTVAL PRIMARY KEY,
    ISSUE_SHORT_NAME STRING(180),
    CURRENCY_TRADE_CODE STRING(180),
    UNIQUE_SECURITY_ID STRING(255) NOT NULL,
    ASSET_IDENTIFIER STRING(255) NOT NULL,
    MATURITY_DATE DATE,
    COUPON_RATE NUMBER(38, 19),
    ISSUE_LONG_NAME STRING(255),
    BLOOMBERG_IDENTIFIER STRING(180),
    ISIN_IDENTIFIER STRING(255),
    SEDOL_IDENTIFIER STRING(255),
    SECURITY_GROUP_CODE STRING(35),
    CALL_PUT_IDENTIFIER STRING(1),
    MULTIPLIER_CURRENT_NUMBER NUMBER(38, 19),
    STRIKE_CURRENT_PRICE NUMBER(38, 19),
    EXCHANGE_TICKER_IDENTIFIER STRING(1000),
    CONTRACT_EXPIRATION_DATE STRING(1000),
    CURRENCY_INCOME_CODE STRING(100),
    COUNTRY_INCORPORATED_CODE STRING(1000),
    SECURITY_TYPE_CODE STRING(255),
    COUNTRY_ISSUE_CODE STRING(180),
    ISSUE_DESCRIPTION_NAME STRING(1000),
    ISSUE_DESCRIPTION_SECONDARY_NAME STRING(100),
    COUNTRY_NRA_TAX_CODE STRING(50),
    COUNTRY_TRADE_CODE STRING(5),
    SOURCE_FILENAME STRING(1000),
    SOURCE_FILE_ROW_NUMBER NUMBER(38),
    INGESTION_TIME TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);