USE SCHEMA RAW;

CREATE OR REPLACE SEQUENCE TRANSACTIONS_SEQ;

CREATE
OR REPLACE TABLE TRANSACTIONS(
    PRIMARY_KEY INT DEFAULT TRANSACTIONS_SEQ.NEXTVAL PRIMARY KEY,
    SPONSOR_ID STRING(50) NOT NULL,
    TRANSACTION_TYPE_CODE STRING(30),
    TRANSACTION_SUB_TYPE_CODE STRING(50),
    CASH_FLOW_CATEGORY_NAME STRING(255) NOT NULL,
    COMMITMENT_TYPE_DESCRIPTION STRING(255),
    CURRENCY_LOCAL_CODE STRING(3),
    ENTITY_CODE STRING(27) NOT NULL,
    ASSET_IDENTIFIER STRING(255) NOT NULL,
    COUPON_RATE NUMBER(38, 19),
    MATURITY_DATE DATE,
    UNIQUE_SECURITY_ID STRING(255) NOT NULL,
    EFFECTIVE_DATE DATE NOT NULL,
    SETTLEMENT_DATE_CONTRACTUAL DATE,
    --UNIT_PRICE NUMBER(38, 19),
    UNIT_PRICE STRING(255), -- updated to String as sample data has "". to be verified.
    UNITS_AMOUNT NUMBER(38, 19),
    NET_LOCAL_AMOUNT NUMBER(38, 19),
    TRADE_DATE_LOCAL_EXCHANGE_RATE NUMBER(38, 19),
    COMMITMENT_EXCLUDED STRING(255), -- added STRING(255)
    RECALLABLE_AMOUNT STRING(255), -- added STRING(255)
    CASH_OR_STOCK STRING(255), -- added STRING(255)
    INTEREST_BOUGHT_SOLD_LOCAL_AMOUNT NUMBER(38, 19),
    SOURCE_TRADE_IDENTIFIER STRING(255),
    TRANSACTION_IDENTIFIER NUMBER(38, 19) NOT NULL,
    SOURCE STRING(12),
    TRANS_CODE_KEY STRING (255) NOT NULL,
    REVERSAL_KEY_AIS STRING(255),    --ADDED NEW COL PER DOCUMENT
    SOURCE_FILENAME STRING(1000),
    SOURCE_FILE_ROW_NUMBER NUMBER(38),
    INGESTION_TIME TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);