USE ROLE SS_DBA;

CREATE
OR REPLACE PIPE SS_DEV.RAW.ACCOUNTPROFILE_PIPE 
AUTO_INGEST = TRUE 
INTEGRATION = 'STATESTREET_INTEGRATION' 
AS COPY INTO ACCOUNTPROFILE
  (
    SPONSOR_ID,
    CURRENCY_BASE_CODE,
    MNTHLY_PERF_EST_METHOD,
    SPECIAL_ENTITY_TYPE,
    INCEPTION_DATE,
    ENTITY_VALUE_EST_METHOD,
    ENTITY_SHORT_NAME,
    ENTITY_CODE,
    INCEPTION_DT_REPORTING,
    ENTITY_NAME,
    COMMINGLED_FLG,
    DAILY_PERF_CNVRSN_DT,
    DAILY_PERF_FLG,
    ENTITY_STATUS_CODE,
    CLOSE_DATE_PERFORMANCE,
    INCEPTION_DT_GASB,
    FISCAL_YEAR_END_MNTH,
    SOURCE_FILENAME,
    SOURCE_FILE_ROW_NUMBER
  )
  FROM (
      SELECT
        T.$1,
        T.$2,
        T.$3,
        T.$4,
        T.$5,
        T.$6,
        T.$7,
        T.$8,
        T.$9,
        T.$10,
        T.$11,
        T.$12,
        T.$13,
        T.$14,
        T.$15,
        T.$16,
        T.$17,
        METADATA$FILENAME,
        METADATA$FILE_ROW_NUMBER
      FROM
        @STATESTREET_AZURE_STAGE_ACCOUNTPROFILE (FILE_FORMAT => SS_FILEFORMAT_CSV) T
    );