USE ROLE SS_DBA;

CREATE
OR REPLACE 
PIPE SS_DEV.RAW.ACCOUNTSECURITIES_PIPE 
AUTO_INGEST = TRUE 
INTEGRATION = 'STATESTREET_INTEGRATION' 
AS COPY INTO ACCOUNTSECURITIES
  (      
    ENTITY_CODE,
    ASSET_IDENTIFIER,
    COUPON_RATE,
    MATURITY_DATE,
    UNIQUE_SECURITY_ID,
    INVESTMENT_VALUE_EST_METHOD,
    MNTHLY_PERF_EST_METHOD,
    LOC_CURRENCY,
    SOURCE_FILENAME,
    SOURCE_FILE_ROW_NUMBER
  )
FROM
  (
    SELECT
      T.$1,
      T.$2,
      T.$3,
      T.$4,
      T.$5,
      T.$6,
      T.$7,
      T.$8,
      METADATA$FILENAME,
      METADATA$FILE_ROW_NUMBER
    FROM
      @STATESTREET_AZURE_STAGE_ACCOUNTSECURITIES (FILE_FORMAT => SS_FILEFORMAT_CSV) T
  );