USE ROLE SS_DBA;

CREATE
OR REPLACE 
PIPE SS_DEV.RAW.CLASSIFICATIONS_PIPE 
AUTO_INGEST = TRUE 
INTEGRATION = 'STATESTREET_INTEGRATION' 
AS COPY INTO CLASSIFICATIONS
  (
      NODE_REF_ID,
      NODE_REF_CODE,
      NODE_REF_DESC,
      NODE_REF_LONG_DESC,
      CLASSIFICATION_SCHEME_NM,
      CLASSIFICATION_LVL_NM,
      ASSET_IDENTIFIER,
      EFFECTIVE_DATE,
      END_DT,
      SOURCE,
      SOURCE_FILENAME,
      SOURCE_FILE_ROW_NUMBER
  )
FROM
  (
    SELECT
      T.$1,
      T.$2,
      T.$3,
      T.$4,
      T.$5,
      T.$6,
      T.$7,
      T.$8,
      T.$9,
      T.$10,
      METADATA$FILENAME,
      METADATA$FILE_ROW_NUMBER
    FROM
      @STATESTREET_AZURE_STAGE_CLASSIFICATIONS (FILE_FORMAT => SS_FILEFORMAT_CSV) T
  );