USE ROLE SS_DBA;

CREATE
OR REPLACE 
PIPE SS_DEV.RAW.FXRATES_PIPE 
AUTO_INGEST = TRUE 
INTEGRATION = 'STATESTREET_INTEGRATION' 
AS COPY INTO FXRATES
  (
    EXCHANGE_SOURCE_CODE,
    CURRENCY_PAIR_CODE,
    EFFECTIVE_DATE,
    SPOT_RATE,
    SOURCE_FILENAME,
    SOURCE_FILE_ROW_NUMBER
  )
FROM
  (
    SELECT
      T.$1,
      T.$2,
      T.$3,
      T.$4,
      METADATA$FILENAME,
      METADATA$FILE_ROW_NUMBER
    FROM
      @STATESTREET_AZURE_STAGE_FXRATES (FILE_FORMAT => SS_FILEFORMAT_CSV) T
  );