USE ROLE SS_DBA;

CREATE
OR REPLACE 
PIPE SS_DEV.RAW.HOLDINGS_PIPE 
AUTO_INGEST = TRUE 
INTEGRATION = 'STATESTREET_INTEGRATION' 
AS COPY INTO HOLDINGS
  (
    SPONSOR_ID,
    ENTITY_CODE,
    ASSET_IDENTIFIER,
    COUPON_RATE,
    MATURITY_DATE,
    UNIQUE_SECURITY_ID,
    EFFECTIVE_DATE,
    UNIT_PRICE,
    UNITS_AMOUNT,
    MARKET_VALUE_DIRTY_LOCAL_AMOUNT,
    INCOME_ACCRUED_LOCAL_AMOUNT,
    ACCT_LEVEL,
    SOURCE,
    LOC_CURRENCY,
    SOURCE_FILENAME,
    SOURCE_FILE_ROW_NUMBER
  )
FROM
  (
    SELECT
      T.$1,
      T.$2,
      T.$3,
      T.$4,
      T.$5,
      T.$6,
      T.$7,
      T.$8,
      T.$9,
      T.$10,
      T.$11,
      T.$12,
      T.$13,
      T.$14,
      METADATA$FILENAME,
      METADATA$FILE_ROW_NUMBER
    FROM
      @STATESTREET_AZURE_STAGE_HOLDINGS (FILE_FORMAT => SS_FILEFORMAT_CSV) T
  );