USE ROLE SS_DBA;

CREATE
OR REPLACE 
PIPE SS_DEV.RAW.INDEXTOTAL_PIPE 
AUTO_INGEST = TRUE 
INTEGRATION = 'STATESTREET_INTEGRATION' 
AS COPY INTO INDEXTOTAL
 (
    ENTITY_CODE,
    EFFECTIVE_DATE,
    DATATYPE,
    MARKET_CAP,
    INDEX_LEVEL,
    CURRENCY_CODE,
    RETURN,
    SOURCE_FILENAME,
    SOURCE_FILE_ROW_NUMBER
 )
FROM
  (
    SELECT
      T.$1,
      T.$2,
      T.$3,
      T.$4,
      T.$5,
      T.$6,
      T.$7,
      METADATA$FILENAME,
      METADATA$FILE_ROW_NUMBER
    FROM
      @STATESTREET_AZURE_STAGE_INDEXTOTAL (FILE_FORMAT => SS_FILEFORMAT_CSV) T
  );