USE ROLE SS_DBA;

CREATE
OR REPLACE 
PIPE SS_DEV.RAW.PORTFOLIONODE_PIPE 
AUTO_INGEST = TRUE 
INTEGRATION = 'STATESTREET_INTEGRATION' 
AS COPY INTO PORTFOLIONODE
  (
    SPONSOR_ID,
    ENTITY_CODE,
    ENTITY_SHORT_NAME,
    EFFECTIVE_DATE,
    CLSSFN_HIER_SCHM_ID,
    CLSSFN_HIER_SCHM_NM,
    CLSSFN_HIER_LVL2_NM,
    CLSSFN_HIER_LVL3_NM,
    CLSSFN_HIER_LVL4_NM,
    CLSSFN_HIER_LVL5_NM,
    CLSSFN_HIER_LVL6_NM,
    CLSSFN_HIER_LVL7_NM,
    CLSSFN_HIER_LVL8_NM,
    CLSSFN_HIER_LVL9_NM,
    CLSSFN_HIER_LVL10_NM,
    CLSSFN_HIER_LVL11_NM,
    CLSSFN_HIER_LVL12_NM,
    EMV,
    ASSET_WGHT_AMT,
    SOURCE_FILENAME,
    SOURCE_FILE_ROW_NUMBER
  )
  FROM
    (
      SELECT
        T.$1,
        T.$2,
        T.$3,
        T.$4,
        T.$5,
        T.$6,
        T.$7,
        T.$8,
        T.$9,
        T.$10,
        T.$11,
        T.$12,
        T.$13,
        T.$14,
        T.$15,
        T.$16,
        T.$17,
        T.$18,
        T.$19,
        METADATA$FILENAME,
        METADATA$FILE_ROW_NUMBER
      FROM
        @STATESTREET_AZURE_STAGE_PORTFOLIONODE (FILE_FORMAT => SS_FILEFORMAT_CSV) T
    );