USE ROLE SS_DBA;

CREATE
OR REPLACE 
PIPE SS_DEV.RAW.SMF_PIPE 
AUTO_INGEST = TRUE 
INTEGRATION = 'STATESTREET_INTEGRATION' 
AS COPY INTO SMF
  (
    ISSUE_SHORT_NAME,
    CURRENCY_TRADE_CODE,
    UNIQUE_SECURITY_ID,
    ASSET_IDENTIFIER,
    MATURITY_DATE,
    COUPON_RATE,
    ISSUE_LONG_NAME,
    BLOOMBERG_IDENTIFIER,
    ISIN_IDENTIFIER,
    SEDOL_IDENTIFIER,
    SECURITY_GROUP_CODE,
    CALL_PUT_IDENTIFIER,
    MULTIPLIER_CURRENT_NUMBER,
    STRIKE_CURRENT_PRICE,
    EXCHANGE_TICKER_IDENTIFIER,
    CONTRACT_EXPIRATION_DATE,
    CURRENCY_INCOME_CODE,
    COUNTRY_INCORPORATED_CODE,
    SECURITY_TYPE_CODE,
    COUNTRY_ISSUE_CODE,
    ISSUE_DESCRIPTION_NAME,
    ISSUE_DESCRIPTION_SECONDARY_NAME,
    COUNTRY_NRA_TAX_CODE,
    COUNTRY_TRADE_CODE,
    SOURCE_FILENAME,
    SOURCE_FILE_ROW_NUMBER
  )
FROM
  (
    SELECT
      T.$1,
      T.$2,
      T.$3,
      T.$4,
      T.$5,
      T.$6,
      T.$7,
      T.$8,
      T.$9,
      T.$10,
      T.$11,
      T.$12,
      T.$13,
      T.$14,
      T.$15,
      T.$16,
      T.$17,
      T.$18,
      T.$19,
      T.$20,
      T.$21,
      T.$22,
      T.$23,
      T.$24,
      METADATA$FILENAME,
      METADATA$FILE_ROW_NUMBER
    FROM
      @STATESTREET_AZURE_STAGE_SMF (FILE_FORMAT => SS_FILEFORMAT_CSV) T
  );