USE ROLE SS_DBA;

CREATE
OR REPLACE 
PIPE SS_DEV.RAW.TRANSACTIONS_PIPE 
AUTO_INGEST = TRUE 
INTEGRATION = 'STATESTREET_INTEGRATION' 
AS COPY INTO TRANSACTIONS
	(
		SPONSOR_ID,
		TRANSACTION_TYPE_CODE,
		TRANSACTION_SUB_TYPE_CODE,
		CASH_FLOW_CATEGORY_NAME,
		COMMITMENT_TYPE_DESCRIPTION,
		CURRENCY_LOCAL_CODE,
		ENTITY_CODE,
		ASSET_IDENTIFIER,
		COUPON_RATE,
		MATURITY_DATE,
		UNIQUE_SECURITY_ID,
		EFFECTIVE_DATE,
		SETTLEMENT_DATE_CONTRACTUAL,
		UNIT_PRICE,
		UNITS_AMOUNT,
		NET_LOCAL_AMOUNT,
		TRADE_DATE_LOCAL_EXCHANGE_RATE,
		COMMITMENT_EXCLUDED,
		RECALLABLE_AMOUNT,
		CASH_OR_STOCK,
		INTEREST_BOUGHT_SOLD_LOCAL_AMOUNT,
		SOURCE_TRADE_IDENTIFIER,
		TRANSACTION_IDENTIFIER,
		SOURCE,
		TRANS_CODE_KEY,
		REVERSAL_KEY_AIS,	
		SOURCE_FILENAME,
		SOURCE_FILE_ROW_NUMBER
	)
FROM
	(
		SELECT
			T.$1,
			T.$2,
			T.$3,
			T.$4,
			T.$5,
			T.$6,
			T.$7,
			T.$8,
			T.$9,
			T.$10,
			T.$11,
			T.$12,
			T.$13,
			T.$14,
			T.$15,
			T.$16,
			T.$17,
			T.$18,
			T.$19,
			T.$20,
			T.$21,
			T.$22,
			T.$23,
			T.$24,
			T.$25,
			T.$26,
			METADATA$FILENAME,
			METADATA$FILE_ROW_NUMBER
		FROM
			@STATESTREET_AZURE_STAGE_TRANSACTIONS (FILE_FORMAT => SS_FILEFORMAT_CSV) T
	);