USE SCHEMA CURRENT_RAW;

CREATE OR REPLACE VIEW ACCOUNTPROFILE 
COMMENT = 'VIEW TO FETCH THE MOST RECENT RECORDS' 
AS
SELECT
SPONSOR_ID,
CURRENCY_BASE_CODE,
MNTHLY_PERF_EST_METHOD,
SPECIAL_ENTITY_TYPE,
INCEPTION_DATE,
ENTITY_VALUE_EST_METHOD,
ENTITY_SHORT_NAME,
ENTITY_CODE,
INCEPTION_DT_REPORTING,
ENTITY_NAME,
COMMINGLED_FLG,
DAILY_PERF_CNVRSN_DT,
DAILY_PERF_FLG,
ENTITY_STATUS_CODE,
CLOSE_DATE_PERFORMANCE,
INCEPTION_DT_GASB,
FISCAL_YEAR_END_MNTH,
SOURCE_FILENAME,
INGESTION_TIME
FROM
    (
        SELECT
            *,
            ROW_NUMBER() OVER(
                PARTITION BY ENTITY_CODE
                ORDER BY
                    INGESTION_TIME DESC
            ) AS RN
        FROM
            RAW.ACCOUNTPROFILE
    )
WHERE
    RN = 1
ORDER BY
    ENTITY_CODE,
    INGESTION_TIME;