USE SCHEMA CURRENT_RAW;

CREATE OR REPLACE VIEW ACCOUNTSECURITIES 
COMMENT = 'VIEW TO FETCH THE MOST RECENT RECORDS' 
AS
SELECT
ENTITY_CODE,
ASSET_IDENTIFIER,
COUPON_RATE,
MATURITY_DATE,
UNIQUE_SECURITY_ID,
INVESTMENT_VALUE_EST_METHOD,
MNTHLY_PERF_EST_METHOD,
LOC_CURRENCY,
SOURCE_FILENAME,
INGESTION_TIME
FROM
    (
        SELECT
            *,
            ROW_NUMBER() OVER(
                PARTITION BY ENTITY_CODE, UNIQUE_SECURITY_ID -- check the correctness of column used
                ORDER BY
                    INGESTION_TIME DESC
            ) AS RN
        FROM
            RAW.ACCOUNTSECURITIES
    )
WHERE
    RN = 1
ORDER BY
    ENTITY_CODE,
    UNIQUE_SECURITY_ID,
    INGESTION_TIME;