USE SCHEMA CURRENT_RAW;

CREATE OR REPLACE VIEW CHARACTERISTICS 
COMMENT = 'VIEW TO FETCH THE MOST RECENT RECORDS' 
AS
SELECT
ANALYTICS_SOURCE,
EFFECTIVE_DATE,
AVG_LIFE,
BETA_FUND,
BETA_PRICE,
BUY_HOLD_DLY_RT,
BUY_HOLD_MNTH_RT,
COMM_SHRS_OUT,
CONVEXITY,
COUPON,
CURR_ASSETS_TOT,
CURR_LIAB_TOT,
CURR_YLD,
DEBT_CAP_RATIO,
DIV_YLD,
DIV_YLD_5_YR_GRWTH,
DUR_MOD,
DUR_OPT_ADJ,
EBS_5_YR_GRWTH_IBES,
EBS_5_YR_STAB,
EPS,
EPS_5_YR_GRWTH,
EPS_CHNG_12_MTHS,
EPS_FISC_1_YR_EST,
EPS_FISC_2_YR_EST,
EPS_GRWTH_4_YR,
EPS_TR_12_MTH,
FISCAL_YR,
FORWARD_PE,
LT_DEBT_TO_ASSETS,
LT_DEBT_TO_EQTY,
MKT_CAP,
MKT_CAP_480,
MOODY_RATING,
MOODY_VENDED_RATING,
NET_INC_LOSS,
NET_PROF_MG,
NET_SALES,
OAS,
PAYOUT_RATIO,
PE,
PE_WO_NEGATIVE,
PRC_EPS_FY1_EST_IBES,
PRICE_TO_BOOK,
PRICE_TO_CASH_FL,
PRICE_TO_EBITDA,
PRICE_TO_SALES,
QUICK_RATIO,
ROA,
ROE,
ASSET_IDENTIFIER,
LOC_CURRENCY,
SH_HOLDER_EQ,
SP_RATING,
SP_VENDED_RATING,
STD_4_YR_EPS_GRWTH,
STD_5_YR_YLD_AVG,
STD_BK_PRICE_RATIO,
STD_ER_PRICE_RATIO,
STD_LT_DEBT_ASSETS_RATIO,
STD_NAT_LOG_MKT_CAP,
TIME_TO_MAT,
TOTAL_ASSETS,
TOTAL_DEBT,
YLD_AVG_5_YR,
YTM,
YTM_OR_CALL,
SOURCE_FILENAME,
INGESTION_TIME
FROM
    (
        SELECT
            *,
            ROW_NUMBER() OVER(
                PARTITION BY EFFECTIVE_DATE, ASSET_IDENTIFIER -- check the correctness of column used
                ORDER BY
                    INGESTION_TIME DESC
            ) AS RN
        FROM
            RAW.CHARACTERISTICS
    )
WHERE
    RN = 1
ORDER BY
    EFFECTIVE_DATE,
    ASSET_IDENTIFIER,
    INGESTION_TIME;