USE SCHEMA CURRENT_RAW;

CREATE OR REPLACE VIEW CLASSIFICATIONS 
COMMENT = 'VIEW TO FETCH THE MOST RECENT RECORDS' 
AS
SELECT
NODE_REF_ID,
NODE_REF_CODE,
NODE_REF_DESC,
NODE_REF_LONG_DESC,
CLASSIFICATION_SCHEME_NM,
CLASSIFICATION_LVL_NM,
ASSET_IDENTIFIER,
EFFECTIVE_DATE,
END_DT,
SOURCE,
SOURCE_FILENAME,
INGESTION_TIME
FROM
    (
        SELECT
            *,
            ROW_NUMBER() OVER(
                PARTITION BY NODE_REF_ID -- check the correctness of column used
                ORDER BY
                    INGESTION_TIME DESC
            ) AS RN
        FROM
            RAW.CLASSIFICATIONS
    )
WHERE
    RN = 1
ORDER BY
    NODE_REF_ID,
    INGESTION_TIME;