USE SCHEMA CURRENT_RAW;

CREATE OR REPLACE VIEW COUNTRYCALENDAR 
COMMENT = 'VIEW TO FETCH THE MOST RECENT RECORDS' 
AS
SELECT
CALENDAR_DT,
COUNTRY_CD,
DAY_TYPE_CD,
MONTH_END_CD,
NEXT_BUSINESS_DT,
NEXT_MONTH_END_DT,
PRIOR_BUSINESS_DATE,
PRIOR_MONTH_END_DT,
SOURCE_FILENAME,
INGESTION_TIME
FROM
    (
        SELECT
            *,
            ROW_NUMBER() OVER(
                PARTITION BY CALENDAR_DT, COUNTRY_CD -- check the correctness of column used
                ORDER BY
                    INGESTION_TIME DESC
            ) AS RN
        FROM
            RAW.COUNTRYCALENDAR
    )
WHERE
    RN = 1
ORDER BY
    CALENDAR_DT,
    COUNTRY_CD,
    INGESTION_TIME;