USE SCHEMA CURRENT_RAW;

CREATE OR REPLACE VIEW HOLDINGS 
COMMENT = 'VIEW TO FETCH THE MOST RECENT RECORDS' 
AS
SELECT
SPONSOR_ID,
ENTITY_CODE,
ASSET_IDENTIFIER,
COUPON_RATE,
MATURITY_DATE,
UNIQUE_SECURITY_ID,
EFFECTIVE_DATE,
UNIT_PRICE,
UNITS_AMOUNT,
MARKET_VALUE_DIRTY_LOCAL_AMOUNT,
INCOME_ACCRUED_LOCAL_AMOUNT,
ACCT_LEVEL,
SOURCE,
LOC_CURRENCY,
SOURCE_FILENAME,
INGESTION_TIME
FROM
    (
        SELECT
            *,
            ROW_NUMBER() OVER(
                PARTITION BY ENTITY_CODE, ASSET_IDENTIFIER, EFFECTIVE_DATE -- check the correctness of column used
                ORDER BY
                    INGESTION_TIME DESC
            ) AS RN
        FROM
            RAW.HOLDINGS
    )
WHERE
    RN = 1
ORDER BY
    ENTITY_CODE,
    ASSET_IDENTIFIER,
    EFFECTIVE_DATE,
    INGESTION_TIME;