USE SCHEMA CURRENT_RAW;

CREATE OR REPLACE VIEW INDEXSECURITY 
COMMENT = 'VIEW TO FETCH THE MOST RECENT RECORDS' 
AS
SELECT
ENTITY_CODE,
EFFECTIVE_DATE,
DATATYPE,
INDEX_TYPE,
ASSET_IDENTIFIER,
COUPON_RATE,
MATURITY_DATE,
CURRENCY_CODE,
BEG_MKT_VALUE_BASE,
END_MKT_VALUE_BASE,
BEG_MARKET_CAP_BASE,
END_MARKET_CAP_BASE,
PRICE_BASE,
RETURN_BASE,
LOC_CURRENCY,
BEG_MKT_VALUE_LOC,
END_MKT_VALUE_LOC,
BEG_MARKET_CAP_LOC,
END_MARKET_CAP_LOC,
PRICE_LOC,
RETURN_LOC,
SHARES_PERF,
SOURCE_FILENAME,
INGESTION_TIME
FROM
    (
        SELECT
            *,
            ROW_NUMBER() OVER(
                PARTITION BY 
                ENTITY_CODE, -- check the correctness of column used
                ASSET_IDENTIFIER, -- check the correctness of column used
                EFFECTIVE_DATE -- check the correctness of column used
                ORDER BY
                    INGESTION_TIME DESC
            ) AS RN
        FROM
            RAW.INDEXSECURITY
    )
WHERE
    RN = 1
ORDER BY
    ENTITY_CODE,
    ASSET_IDENTIFIER,
    EFFECTIVE_DATE,
    INGESTION_TIME;