USE SCHEMA CURRENT_RAW;

CREATE OR REPLACE VIEW PORTFOLIONODE 
COMMENT = 'VIEW TO FETCH THE MOST RECENT RECORDS' 
AS
SELECT
SPONSOR_ID,
ENTITY_CODE,
ENTITY_SHORT_NAME,
EFFECTIVE_DATE,
CLSSFN_HIER_SCHM_ID,
CLSSFN_HIER_SCHM_NM,
CLSSFN_HIER_LVL2_NM,
CLSSFN_HIER_LVL3_NM,
CLSSFN_HIER_LVL4_NM,
CLSSFN_HIER_LVL5_NM,
CLSSFN_HIER_LVL6_NM,
CLSSFN_HIER_LVL7_NM,
CLSSFN_HIER_LVL8_NM,
CLSSFN_HIER_LVL9_NM,
CLSSFN_HIER_LVL10_NM,
CLSSFN_HIER_LVL11_NM,
CLSSFN_HIER_LVL12_NM,
EMV,
ASSET_WGHT_AMT,
SOURCE_FILENAME,
INGESTION_TIME
FROM
    (
        SELECT
            *,
            ROW_NUMBER() OVER(
                PARTITION BY 
                SPONSOR_ID, -- check the correctness of column used
                ENTITY_CODE, -- check the correctness of column used
                EFFECTIVE_DATE -- check the correctness of column used
                ORDER BY
                    INGESTION_TIME DESC
            ) AS RN
        FROM
            RAW.PORTFOLIONODE
    )
WHERE
    RN = 1
ORDER BY
    SPONSOR_ID,
    ENTITY_CODE,
    EFFECTIVE_DATE,
    INGESTION_TIME;