
SELECT 
    ENTITY_CODE AS ACCOUNTCODE,
    UNIQUE_SECURITY_ID AS SECURITYKEY,
    LOC_CURRENCY AS CURRENCY,
    MNTHLY_PERF_EST_METHOD AS MONTHLYPERFORMANCEESTIMATIONMETHOD,
    INVESTMENT_VALUE_EST_METHOD AS INVESTMENTVALUEESTIMATIONMETHOD,
    DBT_VALID_FROM AS VALIDFROM,
    DBT_VALID_TO AS VALIDTO,
    'STATESTREET' AS LINEAGEKEY

FROM {{ ref('accountsecurities_snapshot') }}