
SELECT 
    UNIQUE_SECURITY_ID AS SECURITYKEY,
    ISSUE_LONG_NAME AS SECURITYLONGNAME,
    ISSUE_SHORT_NAME AS SECURITYSHORTNAME,
    ISSUE_DESCRIPTION_NAME AS SECURITYDESCRIPTIONNAME,
    ISSUE_DESCRIPTION_SECONDARY_NAME AS SECURITYDESCRIPTIONSECONDARYNAME,
    ASSET_IDENTIFIER AS ASSETID,
    SECURITY_GROUP_CODE AS SECURITYGROUPCODE,
    ISIN_IDENTIFIER AS ISIN,
    SEDOL_IDENTIFIER AS SEDOL,
    BLOOMBERG_IDENTIFIER AS BLOOMBERGTICKER,
    CURRENCY_TRADE_CODE AS CURRENCY,
    MATURITY_DATE AS MATURITYDATE,
    COUPON_RATE AS COUPONRATE,
    CURRENCY_INCOME_CODE AS CURRENCYINCOMECODE,
    COUNTRY_INCORPORATED_CODE AS COUNTRYINCORPORATEDCODE,
    SECURITY_TYPE_CODE AS SECURITYTYPECODE,
    COUNTRY_ISSUE_CODE AS COUNTRYISSUECODE,
    COUNTRY_NRA_TAX_CODE AS COUNTRYNRATAXCODE,
    COUNTRY_TRADE_CODE AS COUNTRYTRADECODE,
    'STATESTREET' AS LINEAGEKEY
FROM {{ ref('security_snapshot') }}